/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.PoreskaPrijava;
import domen.PoreskiInspektor;
import domen.PoreskiObveznik;
import domen.StavkaPoreskePrijave;
import domen.VrstaPoreza;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import kom.KomunikacijaSaServerom;
import modeli.ModelTabele;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Milica
 */
public class GlavnaForma extends javax.swing.JFrame {

    PoreskiInspektor pi;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        srediTabelu();
        ucitajCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbVrstaPoreza = new javax.swing.JComboBox();
        cmbPoreskiObveznik = new javax.swing.JComboBox();
        txtGodina = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vrsta poreza");

        jLabel2.setText("Poreski obveznik");

        jLabel3.setText("Godina");

        cmbVrstaPoreza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbPoreskiObveznik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj poresku prijavu");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbVrstaPoreza, 0, 192, Short.MAX_VALUE)
                    .addComponent(cmbPoreskiObveznik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGodina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSacuvaj)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addGap(33, 33, 33)
                                .addComponent(btnObrisi)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbVrstaPoreza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPoreskiObveznik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnSacuvaj)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        int godina = Integer.parseInt(txtGodina.getText());
        VrstaPoreza v = (VrstaPoreza) cmbVrstaPoreza.getSelectedItem();

        if (txtGodina.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti godinu");
            return;
        }
        DodajDialog dd = new DodajDialog(this, true);
        dd.dodaj(v);
        dd.setVisible(true);


    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int red = tabela.getSelectedRow();
        ModelTabele mt = (ModelTabele) tabela.getModel();
        mt.obrisi(red);
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        ModelTabele mt = (ModelTabele) tabela.getModel();
        ArrayList<StavkaPoreskePrijave> lista = mt.getListaStavki();
        if (txtGodina.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti godinu");
            return;
        }
        int godina = Integer.parseInt(txtGodina.getText());

        PoreskiObveznik po = (PoreskiObveznik) cmbPoreskiObveznik.getSelectedItem();

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "lista mora imati bar 1 stavku!");
            return;
        }

        PoreskaPrijava p = new PoreskaPrijava(-1, godina, po, pi, lista);
        
        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(operacije.Operacije.UNESIPRIJAVU);
        kz.setP(p);
        KomunikacijaSaServerom.getKom().posaljiZahtev(kz);
        
       ServerskiOdgovor so = KomunikacijaSaServerom.getKom().prihvatiOdgovor();
       boolean uneo =(boolean) so.getOdgovor();
       if(uneo){
           JOptionPane.showMessageDialog(this, "Uspesno uneta prijava");
       }else{
           JOptionPane.showMessageDialog(this, "Neuspesan unos prijave");
       }
        
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbPoreskiObveznik;
    private javax.swing.JComboBox cmbVrstaPoreza;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtGodina;
    // End of variables declaration//GEN-END:variables

    private void ucitajCB() {
        ArrayList<VrstaPoreza> listaVP = new ArrayList<>();
        ArrayList<PoreskiObveznik> po = new ArrayList<>();

        cmbPoreskiObveznik.removeAllItems();
        cmbVrstaPoreza.removeAllItems();

        KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(operacije.Operacije.VRATIVRSTEIOBVEZNIKE);
        KomunikacijaSaServerom.getKom().posaljiZahtev(kz);
        ServerskiOdgovor so = KomunikacijaSaServerom.getKom().prihvatiOdgovor();

        listaVP = so.getListaVrsti();
        po = so.getListaObveznika();

        for (PoreskiObveznik p : po) {
            cmbPoreskiObveznik.addItem(p);

        }
        for (VrstaPoreza v : listaVP) {
            cmbVrstaPoreza.addItem(v);
        }

    }

    private void srediTabelu() {
        ModelTabele mt = new ModelTabele();
        tabela.setModel(mt);
    }

    boolean dodajUTabelu(StavkaPoreskePrijave s) {
        boolean dodao = false;
        ModelTabele mt = (ModelTabele) tabela.getModel();
        dodao = mt.dodajStavku(s);
        return dodao;
    }

    void setPoreskiInsprektor(PoreskiInspektor p) {
        pi = p;
    }

}
